"use client";

import { useState } from "react";
import TargetProfile from "./TargetProfile";
import HeistPlan from "./HeistPlan";
import ThreatLevel from "./ThreatLevel";
import WhatAICantSteal from "./WhatAICantSteal";
import SeriousModeToggle from "./SeriousModeToggle";
import ShareButton from "./ShareButton";
import type { InterviewData, HeistReport } from "@/lib/types";

interface ReportViewProps {
  interviewData: InterviewData;
  report: HeistReport;
}

export default function ReportView({
  interviewData,
  report,
}: ReportViewProps) {
  const [seriousMode, setSeriousMode] = useState(false);

  return (
    <div className="min-h-screen bg-charcoal">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <header className="mb-8 flex justify-between items-start animate-reveal-1">
          <div>
            <h1 className="text-4xl font-mono text-gold mb-2">
              {seriousMode ? "AI LEVERAGE REPORT" : "HEIST PLAN"}
            </h1>
            <p className="text-muted text-sm font-mono">
              {seriousMode ? "Strategic Analysis" : "Intelligence Briefing"}
            </p>
          </div>
          <div className="flex items-center gap-4">
            <SeriousModeToggle
              enabled={seriousMode}
              onChange={setSeriousMode}
            />
            <ShareButton
              interviewData={interviewData}
              report={report}
              seriousMode={seriousMode}
            />
          </div>
        </header>

        <div className="space-y-8">
          <div className="animate-reveal-2"><TargetProfile profile={report.targetProfile} /></div>
          <div className="animate-reveal-3"><HeistPlan steps={report.heistPlan} /></div>
          <div className="animate-reveal-4"><ThreatLevel threat={report.threatLevel} seriousMode={seriousMode} /></div>
          <div className="animate-reveal-5">
            <WhatAICantSteal
              cantSteal={report.cantSteal}
              serious={report.serious}
              seriousMode={seriousMode}
            />
          </div>
        </div>

        <footer className="mt-12 pt-8 border-t border-fog text-center animate-reveal-6">
          <p className="text-muted text-sm font-mono">
            Generated by AI Job Heist Planner
          </p>
        </footer>
      </div>
    </div>
  );
}
