"use client";

import { useState } from "react";
import type { InterviewData, HeistReport } from "@/lib/types";

interface ShareButtonProps {
  interviewData: InterviewData;
  report: HeistReport;
  seriousMode: boolean;
}

export default function ShareButton({
  interviewData,
  report,
  seriousMode,
}: ShareButtonProps) {
  const [copied, setCopied] = useState(false);

  const generateShareText = () => {
    if (seriousMode) {
      return `AI Leverage Report: ${interviewData.jobTitle}

Leverage Score: ${report.serious.leverageScore}%

Top Opportunities:
${report.serious.opportunities
  .slice(0, 3)
  .map((opp) => `- ${opp.area}: ${opp.action}`)
  .join("\n")}

Generated by AI Job Heist Planner`;
    }

    return `AI Job Heist Plan: ${report.targetProfile.codename}

Threat Level: ${report.threatLevel.overallScore}%
Verdict: ${report.threatLevel.verdict}

${report.cantSteal.headline}
${report.cantSteal.items.map((item) => `- ${item.title}`).join("\n")}

Generated by AI Job Heist Planner`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateShareText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error("Failed to copy:", error);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="px-6 py-2 bg-accent text-light rounded-lg hover:bg-opacity-90 transition-all font-mono text-sm"
    >
      {copied ? "COPIED" : "COPY SUMMARY"}
    </button>
  );
}
