"use client";

import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-charcoal">
      <header className="bg-smoke border-b border-fog p-6">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-gold font-mono hover:opacity-80 transition-opacity">
            AI JOB HEIST PLANNER
          </Link>
          <Link href="/privacy" className="text-muted text-sm hover:text-light transition-colors">
            Privacy Policy
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto p-6 text-light">
        <h1 className="text-2xl font-mono text-gold mb-6">Terms of Service</h1>
        <p className="text-muted text-sm mb-8">Last updated: February 2026</p>

        <div className="space-y-8 text-sm leading-relaxed text-light/90">
          <section className="bg-smoke border border-gold/30 rounded-lg p-5">
            <h2 className="text-lg font-mono text-gold mb-3">Parody &amp; Entertainment Disclaimer</h2>
            <p className="mb-3">
              <strong>AI Job Heist Planner is a work of parody and satire.</strong> It uses
              the comedic framing of a heist movie to explore how artificial intelligence
              relates to your work. The &ldquo;heist plans,&rdquo; &ldquo;threat
              levels,&rdquo; &ldquo;target profiles,&rdquo; and other outputs are fictional
              comedic content, not factual assessments.
            </p>
            <p className="mb-3">
              This tool is <strong>not</strong> a career counseling service, employment
              assessment, workforce planning tool, or professional advisory service of any
              kind. The &ldquo;scores&rdquo; and &ldquo;percentages&rdquo; are generated by
              AI for entertainment purposes and should not be treated as accurate
              predictions about job security, AI capability, or employment outcomes.
            </p>
            <p>
              No robots were actually deployed to steal anyone&apos;s job in the making
              of this tool.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">Acceptance</h2>
            <p>
              By using AI Job Heist Planner, you agree to these Terms of Service and
              our <Link href="/privacy" className="text-gold underline">Privacy Policy</Link>.
              If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">What the service does</h2>
            <p>
              AI Job Heist Planner conducts a short AI-powered interview about your work,
              then generates a satirical &ldquo;Heist Plan&rdquo; report and an optional
              &ldquo;Serious Mode&rdquo; reframing of the same data. Both outputs are
              generated by artificial intelligence and are provided for entertainment and
              informational purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">AI-generated content</h2>
            <p className="mb-3">
              This service is powered by AI (Claude, by Anthropic). All interview
              responses and report content are generated by artificial intelligence.
              AI-generated content may be:
            </p>
            <ul className="list-disc list-inside space-y-1 text-muted ml-2">
              <li>Inaccurate, incomplete, or misleading</li>
              <li>Biased in ways that reflect training data limitations</li>
              <li>Different each time, even for the same inputs</li>
              <li>Inconsistent with expert opinion or real-world outcomes</li>
            </ul>
            <p className="mt-3">
              You should not rely on any output from this tool to make employment,
              career, hiring, or business decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">Prohibited uses</h2>
            <p className="mb-3">You may not use this service to:</p>
            <ul className="list-disc list-inside space-y-1 text-muted ml-2">
              <li>Evaluate employees or candidates for employment decisions</li>
              <li>Make hiring, firing, or workforce reduction decisions</li>
              <li>Produce materials presented as professional career assessments</li>
              <li>Harass, intimidate, or threaten anyone about their job security</li>
              <li>Reverse-engineer, scrape, or abuse the underlying AI systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">Your content</h2>
            <p>
              You retain ownership of the information you provide during the interview.
              By using the service, you grant us a limited license to process your inputs
              through our AI pipeline solely to generate your report. We do not store,
              sell, or share your interview data beyond what is described in our{" "}
              <Link href="/privacy" className="text-gold underline">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">Limitation of liability</h2>
            <p>
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND,
              EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL
              LIABILITY FOR DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT
              LIMITED TO DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.
              THIS INCLUDES ANY DECISIONS YOU MAKE BASED ON THE AI-GENERATED CONTENT.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">Age requirement</h2>
            <p>
              You must be at least 13 years old to use this service. If you are under 18,
              you should use this service only with the involvement of a parent or guardian.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">Changes</h2>
            <p>
              We may update these terms from time to time. Continued use of the service
              after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-mono text-gold mb-3">Contact</h2>
            <p>
              Questions about these terms? Contact us at:{" "}
              <span className="text-gold">rob@nomouthlabs.com</span>
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-fog p-6 mt-12">
        <div className="max-w-3xl mx-auto flex gap-4 text-xs text-muted">
          <Link href="/privacy" className="hover:text-light transition-colors">Privacy</Link>
          <Link href="/terms" className="hover:text-light transition-colors">Terms</Link>
        </div>
      </footer>
    </div>
  );
}
